import Head from 'next/head'
import Link from 'next/link'

export default function Home() {
  return (
    <>
      <Head>
        <title>Tick Charts</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <ul>
        <li>
          <Link href='/area-chart'>Area Chart</Link>
          </li>
          <li>
          <Link href='/bar-chart'>Bar Chart</Link>
          </li>
          <li>
          <Link href='/candle-chart'>Candle Chart</Link>
          </li>
          <li>
          <Link href='/kagi-chart'>Kagi Chart</Link>
          </li>
          <li>
          <Link href='/ohlc-chart'>OHLC Chart</Link>
          </li>
          <li>
          <Link href='/ranko-chart'>Ranko Chart</Link>
          </li>
          <li>
          <Link href='/volume-chart'>Volume Chart</Link>
          </li>
          <li>
          <Link href='/line-and-scatter-chart'>Line and Scatter Chart</Link>
          </li>
          <li>
          <Link href='/points-and-fingure-chart'>Points and Fingure Chart</Link>
          </li>
        </ul>
     </main>
    </>
  )
}
